name: Run Docker
on: workflow_dispatch
    

jobs:
  test-action:
    runs-on: ubuntu-latest
    outputs: 
      name: whoitwas
      description: 'someone'
      value: ${{ start-docker.outputs.GITHUB_OUTPUT }}    
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3.3.0      
        
      - name: start-docker
        id: docker
        uses: ./hello-world-docker-action
        with:
          who-to-greet: beHappy
            
      - name: check output
        run: |
          echo "Result : ${{ whoitwas }}"

