name: Run Docker
on: workflow_dispatch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: start docker
        uses: ./hello-world-docker-action/action.yml
