name: Run Docker
on: workflow_dispatch
    

jobs:
  test-action:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0      
        
      - name: start-docker
        id: docker
        uses: ./hello-world-docker-action
        with:
          who-to-greet: beHappy
            
      - name: check output
        run: |
          echo "Result : ${{ steps.docker.output.GITHUB_OUTPUT }}"

